version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comments-api
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

volumes:
  postgres-data:







