version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comments-api
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqllite3
    stdin_open: true
    tty: true
    volumes:
      - ./:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
    ports:
      - "9000:9000"








